Fixing all eslint errors
Vetrox/squirrelbot pull request #98
Opened 2021-01-28 11:46 UTC by Vetrox

Fixing all warnings and errors found by eslint.

Wontfix: Unfiltered for..in loop
Checks for unfiltered for-in loops. The use of this construct results in processing inherited or unexpected properties. You need to filter own properties with hasOwnProperty() method.

Reason: Popular frameworks like jQuery don't do it either and unless someone overwrites the iterator of an array there is no need for code cluttering by checking for hasOwnProperty in EVERY for..in loop.

2021-01-28 12:44 UTC, roscha444 requested changes

2021-01-28 12:44 UTC, roscha444 commented on api/utility/embeds/functions.js
> +		LOGGER.error(`Error: ${error}`);
please log this with

LOGGER.error(error.stack);

2021-01-28 12:51 UTC, roscha444 commented
You mean this error? 

![grafik](https://user-images.githubusercontent.com/33632422/106140856-9be9ff80-616f-11eb-9314-d767291cd378.png)

If yes? I can disable this check in our ESLint config.

2021-01-28 16:31 UTC, Vetrox commented
yes. That would be good!

2021-01-29 12:53 UTC, roscha444 approved these changes

2021-01-29 18:12 UTC, merged